/**
 * API Route: GET /api/stats
 *
 * Returns pre-computed statistics about Claude Code usage.
 * Stats are generated by the Python CLI's `compute-stats` command.
 *
 * Data Source:
 * - Reads ~/.claude/stats-cache.json (pre-computed by CLI)
 *
 * Response: { stats: StatsCache }
 * - Contains daily activity, token usage by model, costs, etc.
 *
 * Error Response: { error: string } with status 500
 *
 * Note: If stats-cache.json doesn't exist, run the CLI command:
 *   python -m src.cli compute-stats
 */

import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import { homedir } from "os";
import path from "path";
import type { StatsCache } from "@/types";

export async function GET() {
  try {
    // Stats cache is stored at the root of the ~/.claude/ directory
    const claudeDir = path.join(homedir(), ".claude");
    const statsPath = path.join(claudeDir, "stats-cache.json");

    // Read and parse the pre-computed stats
    // This file is generated by: python -m src.cli compute-stats
    const statsContent = await fs.readFile(statsPath, "utf-8");
    const stats: StatsCache = JSON.parse(statsContent);

    return NextResponse.json({ stats });
  } catch (error) {
    console.error("Error reading stats:", error);
    return NextResponse.json(
      { error: "Failed to read stats" },
      { status: 500 }
    );
  }
}
