/**
 * Type definitions for the Claude Sessions Explorer web app.
 *
 * This file defines all TypeScript interfaces used throughout the application.
 * The data originates from Claude Code's local storage at ~/.claude/
 *
 * Data sources:
 * - Stats: ~/.claude/stats-cache.json
 * - Projects: ~/.claude/projects/{project-id}/
 * - Session Index: ~/.claude/projects/{project-id}/sessions-index.json
 * - Session Messages: ~/.claude/projects/{project-id}/{session-id}.jsonl
 * - Session Commits: ~/.claude/projects/{project-id}/.commits.json
 */

// =============================================================================
// STATS CACHE TYPES
// Source: ~/.claude/stats-cache.json
// Pre-computed statistics about Claude Code usage across all sessions
// =============================================================================

/**
 * Daily activity metrics aggregated across all sessions.
 * Used to display usage trends over time on the dashboard.
 */
export interface DailyActivity {
  /** ISO date string (YYYY-MM-DD) */
  date: string;
  /** Total messages exchanged on this day */
  messageCount: number;
  /** Number of unique sessions active on this day */
  sessionCount: number;
  /** Number of tool calls (Bash, Read, Write, etc.) made */
  toolCallCount: number;
}

/**
 * Token usage broken down by model for a specific day.
 * Tracks which AI models were used and how many tokens each consumed.
 */
export interface DailyModelTokens {
  /** ISO date string (YYYY-MM-DD) */
  date: string;
  /** Map of model name to total tokens used (e.g., "claude-sonnet-4-20250514": 50000) */
  tokensByModel: Record<string, number>;
}

/**
 * Aggregate token usage and cost for a specific model.
 * Tracks both input/output tokens and cache efficiency.
 */
export interface ModelUsage {
  /** Tokens sent to the model (prompts, context) */
  inputTokens: number;
  /** Tokens generated by the model (responses) */
  outputTokens: number;
  /** Tokens retrieved from cache (reduces cost) */
  cacheReadInputTokens: number;
  /** Tokens stored in cache for future use */
  cacheCreationInputTokens: number;
  /** Number of web search requests made */
  webSearchRequests: number;
  /** Estimated cost in US dollars */
  costUSD: number;
  /** Maximum context window size for this model */
  contextWindow: number;
  /** Maximum output tokens this model can generate */
  maxOutputTokens?: number;
}

/**
 * Information about the longest session by duration.
 * Displayed as a notable stat on the dashboard.
 */
export interface LongestSession {
  /** Unique session identifier */
  sessionId: string;
  /** Duration in milliseconds */
  duration: number;
  /** Number of messages in the session */
  messageCount: number;
  /** When the session started (ISO timestamp) */
  timestamp: string;
}

/**
 * Complete stats cache structure.
 * This is the root object stored in ~/.claude/stats-cache.json
 * and loaded by the /api/stats endpoint.
 */
export interface StatsCache {
  /** Schema version for backwards compatibility */
  version: number;
  /** When these stats were last computed (ISO timestamp) */
  lastComputedDate: string;
  /** Array of daily activity records */
  dailyActivity: DailyActivity[];
  /** Array of daily token usage by model */
  dailyModelTokens: DailyModelTokens[];
  /** Map of model name to aggregate usage stats */
  modelUsage: Record<string, ModelUsage>;
  /** Total number of sessions across all projects */
  totalSessions: number;
  /** Total messages across all sessions */
  totalMessages: number;
  /** Details about the longest session */
  longestSession: LongestSession;
  /** When the first session was created (ISO timestamp) */
  firstSessionDate: string;
  /** Map of hour (0-23) to message count for time-of-day analysis */
  hourCounts: Record<string, number>;
}

// =============================================================================
// SESSION INDEX TYPES
// Source: ~/.claude/projects/{project-id}/sessions-index.json
// Quick-access metadata about sessions without reading full JSONL files
// =============================================================================

/**
 * Summary entry for a session in the project's session index.
 * Used for listing sessions without loading full message history.
 */
export interface SessionIndexEntry {
  /** Unique session identifier (UUID format) */
  sessionId: string;
  /** Absolute path to the session's JSONL file */
  fullPath: string;
  /** File modification time as Unix timestamp (milliseconds) */
  fileMtime: number;
  /** First user message in the session (truncated for preview) */
  firstPrompt: string;
  /** Total number of messages in the session */
  messageCount: number;
  /** When the session was created (ISO timestamp) */
  created: string;
  /** When the session was last modified (ISO timestamp) */
  modified: string;
  /** Git branch active when session started */
  gitBranch: string;
  /** Absolute path to the project directory */
  projectPath: string;
  /** Whether this is a sidechain session (branched conversation) */
  isSidechain: boolean;
}

/**
 * Session index file structure for a project.
 * Contains metadata for all sessions in a project.
 */
export interface SessionIndex {
  /** Schema version for backwards compatibility */
  version: number;
  /** Array of session summary entries */
  entries: SessionIndexEntry[];
}

// =============================================================================
// PROJECT TYPES
// Derived from directory structure at ~/.claude/projects/
// =============================================================================

/**
 * Project information derived from the projects directory.
 * A project corresponds to a working directory where Claude Code was used.
 */
export interface Project {
  /** URL-encoded project path used as directory name */
  id: string;
  /** Human-readable project name (extracted from path) */
  name: string;
  /** Absolute path to the project's session storage directory */
  path: string;
  /** Number of sessions in this project */
  sessionCount: number;
  /** Most recent session activity (ISO timestamp) */
  lastActivity: string;
}

// =============================================================================
// MESSAGE TYPES
// Source: Individual lines in ~/.claude/projects/{project-id}/{session-id}.jsonl
// Each line is a JSON object representing one message
// =============================================================================

/**
 * Content block within a message.
 * Messages can contain multiple content blocks of different types.
 */
export interface MessageContent {
  /** Content type: "text", "tool_use", or "tool_result" */
  type: string;
  /** Text content (for type="text") */
  text?: string;
  /** Reference to the tool call this result belongs to (for type="tool_result") */
  tool_use_id?: string;
  /** Tool name (for type="tool_use", e.g., "Bash", "Read", "Write") */
  name?: string;
  /** Tool input parameters (for type="tool_use") */
  input?: unknown;
  /** Tool execution result (for type="tool_result") */
  content?: string;
}

/**
 * Core message structure with role and content.
 * Content can be a simple string or array of content blocks.
 */
export interface Message {
  /** Who sent the message: "user" or "assistant" */
  role: "user" | "assistant";
  /** Message content - string for simple text, array for complex messages with tools */
  content: string | MessageContent[];
}

/**
 * Complete session message as stored in JSONL files.
 * Each line in a session's JSONL file represents one SessionMessage.
 */
export interface SessionMessage {
  /** Message sender type */
  type: "user" | "assistant" | string;
  /** Unique identifier for this message */
  uuid: string;
  /** UUID of parent message (for conversation threading) */
  parentUuid: string | null;
  /** Session this message belongs to */
  sessionId: string;
  /** When the message was created (ISO timestamp) */
  timestamp: string;
  /** The actual message content */
  message: Message;
  /** Working directory when message was sent */
  cwd?: string;
  /** Git branch when message was sent */
  gitBranch?: string;
  /** Whether this is a system/meta message (not shown to user) */
  isMeta?: boolean;
}

// =============================================================================
// COMMIT TRACKING TYPES
// Source: ~/.claude/projects/{project-id}/.commits.json
// Git commits made during Claude Code sessions (tracked via hooks)
// =============================================================================

/**
 * Git commit made during a Claude Code session.
 * Tracked by the PostToolUse hook when git commit is executed.
 */
export interface SessionCommit {
  /** Full git commit hash (40 characters) */
  commitHash: string;
  /** Branch the commit was made on */
  branch: string;
  /** Git remote URL (for linking to GitHub/GitLab) */
  repoUrl: string;
  /** Working directory where commit was made */
  cwd: string;
  /** When the commit was made (ISO timestamp) */
  timestamp: string;
}

// =============================================================================
// SESSION WITH FULL DATA
// Combines index entry with loaded messages and commits
// =============================================================================

/**
 * Complete session data including messages and commits.
 * This is the full session loaded when viewing a conversation.
 */
export interface Session {
  /** Unique session identifier */
  id: string;
  /** Project this session belongs to */
  projectId: string;
  /** First user message (preview text) */
  firstPrompt: string;
  /** Total number of messages */
  messageCount: number;
  /** When session was created (ISO timestamp) */
  created: string;
  /** When session was last modified (ISO timestamp) */
  modified: string;
  /** Git branch when session started */
  gitBranch: string;
  /** Full message history (loaded on demand) */
  messages?: SessionMessage[];
  /** Git commits made during this session (loaded on demand) */
  commits?: SessionCommit[];
}

// =============================================================================
// API RESPONSE TYPES
// Wrapper types for API endpoint responses
// =============================================================================

/** Response from GET /api/projects */
export interface ProjectsResponse {
  projects: Project[];
}

/** Response from GET /api/projects/[id] */
export interface ProjectDetailResponse {
  project: Project;
  sessions: SessionIndexEntry[];
}

/** Response from GET /api/sessions/[id] */
export interface SessionResponse {
  session: Session;
}

/** Response from GET /api/stats */
export interface StatsResponse {
  stats: StatsCache;
}
