/**
 * API Route: GET /api/knowledge
 *
 * Lists all projects that have extracted knowledge in the .data directory.
 * Knowledge is generated by the Python CLI's extraction commands.
 *
 * Data Source:
 * - Scans ../.data/generated/ for project subdirectories
 *
 * Response: { projects: Array<{ id: string, name: string }> }
 *
 * Error Response: { error: string } with status 500
 */

import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

export async function GET() {
  try {
    // .data is at the root of the project, one level up from next/
    const dataDir = path.join(process.cwd(), "..", ".data");
    const generatedDir = path.join(dataDir, "generated");

    // Check if the directory exists
    try {
      await fs.access(generatedDir);
    } catch {
      return NextResponse.json({ projects: [] });
    }

    // Each subdirectory in generated/ represents one project
    const projectDirs = await fs.readdir(generatedDir);
    const projects: Array<{ id: string; name: string }> = [];

    for (const dir of projectDirs) {
      const projectPath = path.join(generatedDir, dir);
      const stat = await fs.stat(projectPath);

      if (!stat.isDirectory()) continue;

      // Check if knowledge.json exists for this project
      const knowledgePath = path.join(projectPath, "knowledge.json");
      try {
        await fs.access(knowledgePath);
        projects.push({
          id: dir,
          name: dir,
        });
      } catch {
        // Skip directories without knowledge.json
        continue;
      }
    }

    return NextResponse.json({ projects });
  } catch (error) {
    console.error("Error reading knowledge:", error);
    return NextResponse.json(
      { error: "Failed to read knowledge" },
      { status: 500 }
    );
  }
}
